services:
  trufi-tileserver-gl:
    image: maptiler/tileserver-gl:latest
    container_name: trufi-tileserver-gl
    # ports:
    #   - "80:80"
    volumes:
      - ./data:/data
    command: tileserver-gl -p 80
    restart: unless-stopped

networks:
  default:
    name: trufi-server
    external: true
